### ISSUE TITLE
boto3 refresh creds expired issue

### ISSUE THREAD

**Issue by isichei** [moj-analytical-services/dbtools#8]
On going issue.

Boto3 seems to be able to get the right credentials but something else times.

**Comment by isichei** [comment]
Error in py_call_impl(callable, dots$args, dots$keywords) : 
  RuntimeError: Credentials were refreshed, but the refreshed credentials are still expired.

**Comment by isichei** [comment]
More in-depth rundown of issue:
https://github.com/ministryofjustice/analytics-platform/issues/86

**Comment by davidread** [comment]
This fix was released in dbtools v2.0.2 and requires python library: pydbtools>=1.0.0. (It's mentioned in the changelog, but just cross-referencing it here.)
